// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eModal;

#nullable disable

namespace eModal.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eModal.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Appointment_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Appointment_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Container_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Delivery_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_terminal_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Payment_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Payment_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Pickup_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Receiver_fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver_mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Request_response_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Sending_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source_terminal_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terminal_remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
